
#Health
management:
  endpoints:
    web:
      exposure:
        include: health

#Databases
spring:
  data:
    #Mongo
    mongodb:
      host: mongo-db
      port: 27017
    #Redis
    redis:
      host: redis
      port: 6379

#Security
  security:
    user:
      name: philani
      password: password123