
#Health
management:
  endpoints:
    web:
      exposure:
        include: health

#Database
spring:
  data:
    mongodb:
      host: technical-assessment
      port: 27017
  redis:
    host: redis
    port: 6379

  security:
    user:
      name: philani
      password: password123